language: python
python:
  - "3.6"
cache: pip
dist: xenial 
sudo: true
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y pngquant imagemagick
install:
  - make install
script:
  - make test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output/
  repo: kura/kura.github.io
  target_branch: master
  on:
    branch: master

